/**
 * Dockerfile Template Generator
 *
 * Generates Dockerfiles optimized for different application types.
 */

import type { CloudronAddon, ScaffoldInput } from "../types.js"

/**
 * Base image for all Cloudron packages
 */
const BASE_IMAGE =
  "cloudron/base:5.0.0@sha256:04fd70dbd8ad6149c19de39e35718e024417c3e01dc9c6637eaf4a41ec4e596c"

/**
 * Generate Dockerfile header with base image
 */
function generateHeader(): string {
  return `# Dockerfile for Cloudron Package
# Generated by cloudron_scaffold_package
#
# Build: cloudron build
# Install: cloudron install --image <your-image>
# Logs: cloudron logs -f

FROM ${BASE_IMAGE}

# Set working directory
WORKDIR /app/code
`
}

/**
 * Generate addon-specific setup commands
 */
function generateAddonSetup(addons: CloudronAddon[]): string {
  const lines: string[] = []

  if (addons.includes("mysql") || addons.includes("postgresql")) {
    lines.push("# Database client tools are included in base image")
  }

  if (addons.includes("redis")) {
    lines.push("# Redis client tools are included in base image")
  }

  return lines.length > 0 ? `${lines.join("\n")}\n` : ""
}

/**
 * Generate Node.js specific Dockerfile content
 */
function generateNodejsDockerfile(input: ScaffoldInput): string {
  const { httpPort = 8000, addons = [] } = input

  return `${generateHeader()}
# Node.js Application
# The base image includes Node.js - check version with: node -v

${generateAddonSetup(addons)}
# Copy package files first for better layer caching
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy application code
COPY . .

# Create directories for runtime files
RUN mkdir -p /run/app

# Copy start script
COPY start.sh /app/code/start.sh
RUN chmod +x /app/code/start.sh

# Expose the HTTP port
EXPOSE ${httpPort}

# Start the application
CMD ["/app/code/start.sh"]
`
}

/**
 * Generate PHP specific Dockerfile content
 */
function generatePhpDockerfile(input: ScaffoldInput): string {
  const { httpPort = 8000, addons = [] } = input

  return `${generateHeader()}
# PHP Application with Apache
# The base image includes PHP and Apache

${generateAddonSetup(addons)}
# Install additional PHP extensions if needed
# RUN apt-get update && apt-get install -y php-mysql php-gd && rm -rf /var/lib/apt/lists/*

# Configure Apache to listen on the correct port
RUN sed -i "s/Listen 80/Listen ${httpPort}/" /etc/apache2/ports.conf && \\
    sed -i "s/:80/:${httpPort}/" /etc/apache2/sites-enabled/000-default.conf

# Configure PHP sessions to use /run (writable at runtime)
RUN rm -rf /var/lib/php/sessions && \\
    mkdir -p /run/php/sessions && \\
    ln -s /run/php/sessions /var/lib/php/sessions

# Copy application code
COPY . /app/code/public/

# Set proper ownership for web files
RUN chown -R www-data:www-data /app/code/public

# Copy start script
COPY start.sh /app/code/start.sh
RUN chmod +x /app/code/start.sh

# Expose the HTTP port
EXPOSE ${httpPort}

# Start the application
CMD ["/app/code/start.sh"]
`
}

/**
 * Generate Python specific Dockerfile content
 */
function generatePythonDockerfile(input: ScaffoldInput): string {
  const { httpPort = 8000, addons = [] } = input

  return `${generateHeader()}
# Python Application with Gunicorn
# The base image includes Python 3

${generateAddonSetup(addons)}
# Install Python dependencies
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

# Install gunicorn for production
RUN pip3 install --no-cache-dir gunicorn

# Copy application code
COPY . .

# Create directories for runtime files
RUN mkdir -p /run/app

# Copy start script
COPY start.sh /app/code/start.sh
RUN chmod +x /app/code/start.sh

# Expose the HTTP port
EXPOSE ${httpPort}

# Start the application
CMD ["/app/code/start.sh"]
`
}

/**
 * Generate Java specific Dockerfile content
 */
function generateJavaDockerfile(input: ScaffoldInput): string {
  const { httpPort = 8000, addons = [] } = input

  return `${generateHeader()}
# Java Application
# Note: Java sees host memory, not container limit - set JAVA_OPTS in start.sh

${generateAddonSetup(addons)}
# Install Java (OpenJDK)
RUN apt-get update && \\
    apt-get install -y openjdk-17-jre-headless && \\
    rm -rf /var/lib/apt/lists/*

# Copy application JAR
# Build your JAR first: mvn package or gradle build
COPY target/*.jar /app/code/app.jar

# Create directories for runtime files
RUN mkdir -p /run/app /app/data/logs

# Copy start script
COPY start.sh /app/code/start.sh
RUN chmod +x /app/code/start.sh

# Expose the HTTP port
EXPOSE ${httpPort}

# Start the application
CMD ["/app/code/start.sh"]
`
}

/**
 * Generate Go specific Dockerfile content
 */
function generateGoDockerfile(input: ScaffoldInput): string {
  const { httpPort = 8000, addons = [] } = input

  return `${generateHeader()}
# Go Application
# Go binaries handle signals properly and are self-contained

${generateAddonSetup(addons)}
# Copy pre-built binary
# Build first: CGO_ENABLED=0 go build -o server .
COPY server /app/code/server
RUN chmod +x /app/code/server

# Create directories for runtime files
RUN mkdir -p /run/app

# Copy start script
COPY start.sh /app/code/start.sh
RUN chmod +x /app/code/start.sh

# Expose the HTTP port
EXPOSE ${httpPort}

# Start the application
CMD ["/app/code/start.sh"]
`
}

/**
 * Generate static site Dockerfile content
 */
function generateStaticDockerfile(input: ScaffoldInput): string {
  const { httpPort = 8000 } = input

  return `${generateHeader()}
# Static Site with Nginx
# Serves static files from /app/code/public

# Configure nginx
RUN rm -f /etc/nginx/sites-enabled/*

# Create nginx configuration
RUN echo 'server { \\
    listen ${httpPort}; \\
    server_name _; \\
    root /app/code/public; \\
    index index.html; \\
    \\
    location / { \\
        try_files $uri $uri/ /index.html; \\
    } \\
    \\
    # Cache static assets \\
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ { \\
        expires 1y; \\
        add_header Cache-Control "public, immutable"; \\
    } \\
}' > /etc/nginx/sites-enabled/app.conf

# Copy static files
COPY . /app/code/public/

# Copy start script
COPY start.sh /app/code/start.sh
RUN chmod +x /app/code/start.sh

# Expose the HTTP port
EXPOSE ${httpPort}

# Start the application
CMD ["/app/code/start.sh"]
`
}

/**
 * Generate Dockerfile based on app type
 */
export function generateDockerfile(input: ScaffoldInput): string {
  const { appType } = input

  switch (appType) {
    case "nodejs":
      return generateNodejsDockerfile(input)
    case "php":
      return generatePhpDockerfile(input)
    case "python":
      return generatePythonDockerfile(input)
    case "java":
      return generateJavaDockerfile(input)
    case "go":
      return generateGoDockerfile(input)
    case "static":
      return generateStaticDockerfile(input)
    default:
      // Default to Node.js template
      return generateNodejsDockerfile(input)
  }
}
