/**
 * CloudronManifest.json Template Generator
 */

import type {
  AuthMethod,
  CloudronAddon,
  CloudronManifest,
  ScaffoldInput,
} from "../types.js"

/**
 * Generate addon configuration based on selected addons and auth method
 */
function generateAddons(
  addons: CloudronAddon[],
  authMethod: AuthMethod,
): Record<string, Record<string, unknown>> {
  const addonConfig: Record<string, Record<string, unknown>> = {}

  // Always include localstorage if not explicitly excluded
  if (addons.includes("localstorage") || addons.length === 0) {
    addonConfig.localstorage = {}
  }

  // Database addons
  if (addons.includes("mysql")) {
    addonConfig.mysql = {}
  }
  if (addons.includes("postgresql")) {
    addonConfig.postgresql = {}
  }
  if (addons.includes("mongodb")) {
    addonConfig.mongodb = {}
  }
  if (addons.includes("redis")) {
    addonConfig.redis = {}
  }

  // Email addons
  if (addons.includes("sendmail")) {
    addonConfig.sendmail = {}
  }
  if (addons.includes("recvmail")) {
    addonConfig.recvmail = {}
  }

  // Scheduler addon
  if (addons.includes("scheduler")) {
    addonConfig.scheduler = {}
  }

  // Auth addons based on authMethod
  if (authMethod === "ldap" || addons.includes("ldap")) {
    addonConfig.ldap = {}
  }
  if (authMethod === "oidc" || addons.includes("oidc")) {
    addonConfig.oidc = {}
  }

  return addonConfig
}

/**
 * Generate a CloudronManifest.json from scaffold input
 */
export function generateManifest(input: ScaffoldInput): string {
  const {
    appName,
    appId = `io.cloudron.${appName.toLowerCase().replace(/[^a-z0-9]/g, "")}`,
    version = "1.0.0",
    httpPort = 8000,
    healthCheckPath = "/",
    addons = ["localstorage"],
    authMethod = "none",
    description,
    website,
    memoryLimit,
  } = input

  const manifest: CloudronManifest = {
    manifestVersion: 2,
    id: appId,
    title: appName,
    version,
    httpPort,
    healthCheckPath,
    addons: generateAddons(addons, authMethod),
  }

  // Add optional fields
  if (description) {
    manifest.description = description
  }
  if (website) {
    manifest.website = website
  }
  if (memoryLimit) {
    manifest.memoryLimit = memoryLimit
  }

  // Add optionalSso if no auth method is configured
  if (authMethod === "none") {
    manifest.optionalSso = true
  }

  // Add minBoxVersion for compatibility
  manifest.minBoxVersion = "7.0.0"

  // Generate formatted JSON with comments as a header
  const header = `// CloudronManifest.json
// Generated by cloudron_scaffold_package
// 
// Required fields:
//   - manifestVersion: Always 2
//   - id: Unique reverse-domain identifier
//   - title: Display name
//   - version: Semantic version (x.y.z)
//   - httpPort: Port your app listens on
//   - healthCheckPath: Path for health checks
//   - addons: Required platform services
//
// See: https://docs.cloudron.io/packaging/manifest/
`

  return header + JSON.stringify(manifest, null, 2)
}

/**
 * Generate manifest with inline documentation comments
 */
export function generateManifestWithDocs(input: ScaffoldInput): string {
  const {
    appName,
    appId = `io.cloudron.${appName.toLowerCase().replace(/[^a-z0-9]/g, "")}`,
    version = "1.0.0",
    httpPort = 8000,
    healthCheckPath = "/",
    addons = ["localstorage"],
    authMethod = "none",
    description = `${appName} packaged for Cloudron`,
    website,
    memoryLimit = 256 * 1024 * 1024, // 256MB default
  } = input

  const addonConfig = generateAddons(addons, authMethod)

  // Build manifest object with documentation
  const lines: string[] = [
    "{",
    '  "manifestVersion": 2,',
    `  "id": "${appId}",`,
    `  "title": "${appName}",`,
    `  "version": "${version}",`,
    `  "description": "${description}",`,
  ]

  if (website) {
    lines.push(`  "website": "${website}",`)
  }

  lines.push(
    `  "httpPort": ${httpPort},`,
    `  "healthCheckPath": "${healthCheckPath}",`,
    `  "memoryLimit": ${memoryLimit},`,
  )

  if (authMethod === "none") {
    lines.push('  "optionalSso": true,')
  }

  lines.push('  "minBoxVersion": "7.0.0",')

  // Add addons
  lines.push('  "addons": {')
  const addonEntries = Object.entries(addonConfig)
  addonEntries.forEach(([name, config], index) => {
    const comma = index < addonEntries.length - 1 ? "," : ""
    if (Object.keys(config).length === 0) {
      lines.push(`    "${name}": {}${comma}`)
    } else {
      lines.push(`    "${name}": ${JSON.stringify(config)}${comma}`)
    }
  })
  lines.push("  }")

  lines.push("}")

  return lines.join("\n")
}
