/**
 * start.sh Template Generator
 *
 * Generates startup scripts with proper signal handling,
 * first-run initialization, and addon environment variable usage.
 */

import type {
  AuthMethod,
  CloudronAddon,
  ScaffoldAppType,
  ScaffoldInput,
} from "../types.js"

/**
 * Generate the script header with bash settings
 */
function generateHeader(): string {
  return `#!/bin/bash
# start.sh - Cloudron Application Startup Script
# Generated by cloudron_scaffold_package
#
# This script runs as root and should:
# 1. Perform first-run initialization
# 2. Set up file permissions
# 3. Start the application as non-root user
#
# Key directories:
#   /app/code  - Application code (read-only)
#   /app/data  - Persistent storage (requires localstorage addon)
#   /run       - Runtime files (not persisted)
#   /tmp       - Temporary files (not persisted)

set -eu

`
}

/**
 * Generate first-run initialization block
 */
function generateFirstRunInit(addons: CloudronAddon[]): string {
  const lines: string[] = [
    "# First-run initialization",
    "if [[ ! -f /app/data/.initialized ]]; then",
    '    echo "==> First run detected, initializing..."',
    "",
  ]

  // Add database initialization hints based on addons
  if (addons.includes("mysql")) {
    lines.push(
      "    # MySQL database is available via CLOUDRON_MYSQL_* env vars",
    )
    lines.push(
      "    # Example: mysql -h $CLOUDRON_MYSQL_HOST -u $CLOUDRON_MYSQL_USERNAME -p$CLOUDRON_MYSQL_PASSWORD $CLOUDRON_MYSQL_DATABASE < schema.sql",
    )
    lines.push("")
  }

  if (addons.includes("postgresql")) {
    lines.push(
      "    # PostgreSQL database is available via CLOUDRON_POSTGRESQL_* env vars",
    )
    lines.push(
      "    # Example: PGPASSWORD=$CLOUDRON_POSTGRESQL_PASSWORD psql -h $CLOUDRON_POSTGRESQL_HOST -U $CLOUDRON_POSTGRESQL_USERNAME $CLOUDRON_POSTGRESQL_DATABASE < schema.sql",
    )
    lines.push("")
  }

  if (addons.includes("mongodb")) {
    lines.push("    # MongoDB is available via CLOUDRON_MONGODB_* env vars")
    lines.push("    # Connection URL: $CLOUDRON_MONGODB_URL")
    lines.push("")
  }

  lines.push("    # Create required directories")
  lines.push("    mkdir -p /app/data/config")
  lines.push("    mkdir -p /run/app")
  lines.push("")
  lines.push("    # Mark as initialized")
  lines.push("    touch /app/data/.initialized")
  lines.push('    echo "==> Initialization complete"')
  lines.push("fi")
  lines.push("")

  return lines.join("\n")
}

/**
 * Generate environment variable setup for addons
 *
 * Note: The ${...} patterns in strings below are intentional bash variable
 * references that will be in the generated shell script, not JS template literals.
 */
function generateEnvSetup(
  addons: CloudronAddon[],
  authMethod: AuthMethod,
): string {
  const lines: string[] = ["# Export environment variables for the application"]

  if (addons.includes("mysql")) {
    lines.push("")
    lines.push("# MySQL connection")
    lines.push(
      'export DATABASE_URL="mysql://${CLOUDRON_MYSQL_USERNAME}:${CLOUDRON_MYSQL_PASSWORD}@${CLOUDRON_MYSQL_HOST}:${CLOUDRON_MYSQL_PORT}/${CLOUDRON_MYSQL_DATABASE}"',
    )
  }

  if (addons.includes("postgresql")) {
    lines.push("")
    lines.push("# PostgreSQL connection")
    lines.push(
      'export DATABASE_URL="postgresql://${CLOUDRON_POSTGRESQL_USERNAME}:${CLOUDRON_POSTGRESQL_PASSWORD}@${CLOUDRON_POSTGRESQL_HOST}:${CLOUDRON_POSTGRESQL_PORT}/${CLOUDRON_POSTGRESQL_DATABASE}"',
    )
  }

  if (addons.includes("mongodb")) {
    lines.push("")
    lines.push("# MongoDB connection")
    lines.push('export MONGO_URL="${CLOUDRON_MONGODB_URL}"')
  }

  if (addons.includes("redis")) {
    lines.push("")
    lines.push("# Redis connection")
    lines.push(
      'export REDIS_URL="redis://:${CLOUDRON_REDIS_PASSWORD}@${CLOUDRON_REDIS_HOST}:${CLOUDRON_REDIS_PORT}"',
    )
  }

  if (addons.includes("sendmail")) {
    lines.push("")
    lines.push("# SMTP configuration for sending email")
    lines.push('export SMTP_HOST="${CLOUDRON_MAIL_SMTP_SERVER}"')
    lines.push('export SMTP_PORT="${CLOUDRON_MAIL_SMTP_PORT}"')
    lines.push('export SMTP_USER="${CLOUDRON_MAIL_SMTP_USERNAME}"')
    lines.push('export SMTP_PASS="${CLOUDRON_MAIL_SMTP_PASSWORD}"')
    lines.push('export SMTP_FROM="${CLOUDRON_MAIL_FROM}"')
  }

  if (authMethod === "ldap" || addons.includes("ldap")) {
    lines.push("")
    lines.push("# LDAP authentication")
    lines.push('export LDAP_URL="${CLOUDRON_LDAP_URL}"')
    lines.push('export LDAP_BIND_DN="${CLOUDRON_LDAP_BIND_DN}"')
    lines.push('export LDAP_BIND_PASSWORD="${CLOUDRON_LDAP_BIND_PASSWORD}"')
    lines.push('export LDAP_USERS_BASE_DN="${CLOUDRON_LDAP_USERS_BASE_DN}"')
  }

  if (authMethod === "oidc" || addons.includes("oidc")) {
    lines.push("")
    lines.push("# OpenID Connect authentication")
    lines.push('export OIDC_ISSUER="${CLOUDRON_OIDC_ISSUER}"')
    lines.push('export OIDC_CLIENT_ID="${CLOUDRON_OIDC_CLIENT_ID}"')
    lines.push('export OIDC_CLIENT_SECRET="${CLOUDRON_OIDC_CLIENT_SECRET}"')
  }

  lines.push("")
  return lines.join("\n")
}

/**
 * Generate file ownership setup
 */
function generateOwnershipSetup(): string {
  return `# Set proper file ownership
echo "==> Setting file ownership..."
chown -R cloudron:cloudron /app/data
chown -R cloudron:cloudron /run/app 2>/dev/null || true

`
}

/**
 * Generate Node.js specific startup
 */
function generateNodejsStartup(httpPort: number): string {
  return `# Start Node.js application as non-root user
echo "==> Starting Node.js application on port ${httpPort}..."
exec /usr/local/bin/gosu cloudron:cloudron node /app/code/server.js
`
}

/**
 * Generate PHP specific startup
 */
function generatePhpStartup(): string {
  return `# Create runtime directories for PHP
mkdir -p /run/php/sessions
chown -R www-data:www-data /run/php

# Start Apache
echo "==> Starting Apache..."
exec /usr/sbin/apache2ctl -D FOREGROUND
`
}

/**
 * Generate Python specific startup
 */
function generatePythonStartup(httpPort: number): string {
  return `# Start Python application with Gunicorn as non-root user
echo "==> Starting Python application on port ${httpPort}..."
exec /usr/local/bin/gosu cloudron:cloudron gunicorn \\
    --bind 0.0.0.0:${httpPort} \\
    --workers 2 \\
    --access-logfile - \\
    --error-logfile - \\
    app:app
`
}

/**
 * Generate Java specific startup
 */
function generateJavaStartup(httpPort: number): string {
  return `# Calculate memory limits for Java
# Java doesn't respect container memory limits by default
ram=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || echo "268435456")
ram_mb=$((ram / 1048576))
heap_mb=$((ram_mb * 75 / 100))  # Use 75% of available memory for heap

export JAVA_OPTS="-Xmx\${heap_mb}m -Xms\${heap_mb}m"

# Start Java application as non-root user
echo "==> Starting Java application on port ${httpPort} with \${heap_mb}MB heap..."
exec /usr/local/bin/gosu cloudron:cloudron java $JAVA_OPTS -jar /app/code/app.jar
`
}

/**
 * Generate Go specific startup
 */
function generateGoStartup(httpPort: number): string {
  return `# Start Go application as non-root user
# Go binaries handle signals properly
echo "==> Starting Go application on port ${httpPort}..."
exec /usr/local/bin/gosu cloudron:cloudron /app/code/server
`
}

/**
 * Generate static site startup
 */
function generateStaticStartup(): string {
  return `# Start Nginx for static file serving
echo "==> Starting Nginx..."
exec nginx -g "daemon off;"
`
}

/**
 * Generate the application startup command based on app type
 */
function generateStartupCommand(
  appType: ScaffoldAppType,
  httpPort: number,
): string {
  switch (appType) {
    case "nodejs":
      return generateNodejsStartup(httpPort)
    case "php":
      return generatePhpStartup()
    case "python":
      return generatePythonStartup(httpPort)
    case "java":
      return generateJavaStartup(httpPort)
    case "go":
      return generateGoStartup(httpPort)
    case "static":
      return generateStaticStartup()
    default:
      return generateNodejsStartup(httpPort)
  }
}

/**
 * Generate complete start.sh script
 */
export function generateStartScript(input: ScaffoldInput): string {
  const {
    appType,
    httpPort = 8000,
    addons = ["localstorage"],
    authMethod = "none",
  } = input

  const sections = [
    generateHeader(),
    generateFirstRunInit(addons),
    generateEnvSetup(addons, authMethod),
    generateOwnershipSetup(),
    generateStartupCommand(appType, httpPort),
  ]

  return sections.join("")
}
