/**
 * Integration Test Template Generator
 *
 * Generates test/test.js for Cloudron package testing.
 */

import type { ScaffoldInput } from "../types.js"

/**
 * Generate integration test file
 */
export function generateTestFile(input: ScaffoldInput): string {
  const { appName, appId, healthCheckPath = "/" } = input

  const safeAppId =
    appId ?? `io.cloudron.${appName.toLowerCase().replace(/[^a-z0-9]/g, "")}`

  return `#!/usr/bin/env node
/* eslint-env mocha */
/* global browser, page */

/**
 * Integration Tests for ${appName}
 * Generated by cloudron_scaffold_package
 *
 * Run with: cd test && npm test
 *
 * Required environment variables:
 *   - USERNAME: Cloudron admin username
 *   - PASSWORD: Cloudron admin password
 */

'use strict';

const execSync = require('child_process').execSync;
const expect = require('expect.js');
const path = require('path');

// Test configuration
const LOCATION = process.env.LOCATION || '${appName.toLowerCase().replace(/[^a-z0-9]/g, "")}test';
const EXEC_ARGS = { cwd: path.resolve(__dirname, '..'), stdio: 'inherit' };
const TIMEOUT = 60000; // 60 seconds

describe('${appName} Application Tests', function () {
    this.timeout(TIMEOUT);

    let app;

    // ==================== Installation Tests ====================

    describe('Installation', function () {
        it('should install the app', function () {
            execSync(\`cloudron install --location \${LOCATION}\`, EXEC_ARGS);
        });

        it('should get app info', function () {
            const result = execSync(\`cloudron inspect --location \${LOCATION}\`);
            app = JSON.parse(result.toString());
            expect(app).to.be.an('object');
            expect(app.id).to.be.ok();
        });

        it('should be reachable', async function () {
            await browser.newPage();
            await page.goto(\`https://\${app.fqdn}${healthCheckPath}\`);
            // Add assertions based on your app's expected response
            // Example: expect(await page.title()).to.contain('${appName}');
        });
    });

    // ==================== Backup/Restore Tests ====================

    describe('Backup and Restore', function () {
        let backupId;

        it('should create a backup', function () {
            execSync(\`cloudron backup create --app \${app.id}\`, EXEC_ARGS);
        });

        it('should list backups', function () {
            const result = execSync(\`cloudron backup list --raw --app \${app.id}\`);
            const backups = JSON.parse(result.toString());
            expect(backups).to.be.an('array');
            expect(backups.length).to.be.greaterThan(0);
            backupId = backups[0].id;
        });

        it('should restore from backup', function () {
            execSync(\`cloudron restore --backup \${backupId} --app \${app.id}\`, EXEC_ARGS);
        });

        it('should be reachable after restore', async function () {
            await page.goto(\`https://\${app.fqdn}${healthCheckPath}\`);
            // Verify app is working after restore
        });
    });

    // ==================== Restart Tests ====================

    describe('Restart', function () {
        it('should restart the app', function () {
            execSync(\`cloudron restart --app \${app.id}\`, EXEC_ARGS);
        });

        it('should be reachable after restart', async function () {
            await page.goto(\`https://\${app.fqdn}${healthCheckPath}\`);
            // Verify app is working after restart
        });
    });

    // ==================== Update Tests ====================

    describe('Update', function () {
        it('should uninstall the app', function () {
            execSync(\`cloudron uninstall --app \${app.id}\`, EXEC_ARGS);
        });

        it('should install previous version from App Store', function () {
            // Skip if not published to App Store yet
            if (!process.env.TEST_UPDATE) {
                this.skip();
                return;
            }
            execSync(\`cloudron install --appstore-id ${safeAppId} --location \${LOCATION}\`, EXEC_ARGS);
        });

        it('should update to current version', function () {
            if (!process.env.TEST_UPDATE) {
                this.skip();
                return;
            }
            execSync(\`cloudron update --app \${LOCATION}\`, EXEC_ARGS);
        });

        it('should be reachable after update', async function () {
            if (!process.env.TEST_UPDATE) {
                this.skip();
                return;
            }
            const result = execSync(\`cloudron inspect --location \${LOCATION}\`);
            app = JSON.parse(result.toString());
            await page.goto(\`https://\${app.fqdn}${healthCheckPath}\`);
        });
    });

    // ==================== Cleanup ====================

    describe('Cleanup', function () {
        it('should uninstall the app', function () {
            // Get current app info if needed
            if (!app) {
                try {
                    const result = execSync(\`cloudron inspect --location \${LOCATION}\`);
                    app = JSON.parse(result.toString());
                } catch (e) {
                    // App might already be uninstalled
                    return;
                }
            }
            execSync(\`cloudron uninstall --app \${app.id}\`, EXEC_ARGS);
        });
    });
});
`
}

/**
 * Generate package.json for test directory
 */
export function generateTestPackageJson(appName: string): string {
  return JSON.stringify(
    {
      name: `${appName.toLowerCase().replace(/[^a-z0-9]/g, "-")}-test`,
      version: "1.0.0",
      description: `Integration tests for ${appName}`,
      scripts: {
        test: "mocha --bail --timeout 60000 test.js",
      },
      dependencies: {
        "expect.js": "^0.3.1",
        mocha: "^10.2.0",
      },
    },
    null,
    2,
  )
}
